/* gen_sine_table.c — build-time generator for src/sine_table.h.
 *
 * Emits a 2049-element single-cycle sine wavetable in .rodata (KICK-15, D-04):
 *   element i = sinf(2*PI*i/2048) for i = 0..2047
 *   element 2048 = element 0 (guard sample -> branch-free linear interp at wrap)
 *
 * The definition is emitted WITHOUT the `static` keyword so that dsp_primitives.c
 * (which includes the generated header) owns the single external definition, and
 * all other translation units reference it via the `extern` decl in
 * dsp_primitives.h. Committing the generated header means CI never regenerates.
 *
 * Build & run:
 *   cc -std=gnu11 -o /tmp/gen_sine tools/gen_sine_table.c -lm
 *   /tmp/gen_sine > src/sine_table.h
 */
#include <stdio.h>
#include <math.h>

#define TABLE_LEN 2048
#define GUARD_LEN (TABLE_LEN + 1) /* 2049 */

int main(void) {
    const float pi = 3.14159265358979323846f;

    printf("/* sine_table.h — GENERATED by tools/gen_sine_table.c. Do not edit by hand. */\n");
    printf("#ifndef OMEGA_SINE_TABLE_H\n");
    printf("#define OMEGA_SINE_TABLE_H\n\n");
    printf("#include <stdalign.h>\n\n");
    printf("/* Single-cycle sine, 2048 samples + 1 guard sample (t[2048]==t[0]).\n");
    printf(" * Non-static: dsp_primitives.c owns this definition; other TUs use extern. */\n");
    printf("const float _Alignas(16) g_sine_table[%d] = {\n", GUARD_LEN);

    for (int i = 0; i < GUARD_LEN; i++) {
        int src = i % TABLE_LEN; /* index 2048 duplicates index 0 */
        float v = sinf(2.0f * pi * (float)src / (float)TABLE_LEN);
        /* %.9g preserves full float precision round-trip; append 'f' suffix. */
        printf("    %.9gf%s\n", (double)v, (i + 1 < GUARD_LEN) ? "," : "");
    }

    printf("};\n\n");
    printf("#endif /* OMEGA_SINE_TABLE_H */\n");
    return 0;
}
