/* gen_wavetables.c — build-time generator for src/wavetables.h.
 *
 * Emits g_wavetables[NUM_WAVES][BANDS][2049] in .rodata (KICK-15, D-04),
 * mirroring gen_sine_table.c exactly:
 *   - each wave is a single cycle of WT_LEN=2048 samples + 1 guard sample
 *     (element 2048 == element 0) for branch-free linear-interp at the wrap.
 *   - literals printed with %.9e so the 'f' suffix is always a valid float
 *     literal (%.9g can print bare "0"/"1" -> "0f", an invalid constant;
 *     STATE.md A-01).
 *   - the definition is NON-static: dsp_primitives.c owns the single external
 *     definition (via #include "wavetables.h"); other TUs use the extern decl
 *     in dsp_primitives.h.
 *
 * NUM_WAVES / BANDS MUST match the macros in src/dsp_primitives.h.
 * The waves are the factory palette shared by WTR/DIG/ANA/HRD/USR:
 *   0 SINE     — pure fundamental (ANA warm / WTR clean body)
 *   1 TRIANGLE — soft odd harmonics
 *   2 SAW-ish  — band-limited-ish ramp (rich, for morph targets)
 *   3 SQUARE   — hollow odd harmonics (DIG chip character)
 *   4 DIGITAL  — bit-reduced/stepped sine (DIG retro crunch)
 *   5 ANALOG   — softly saturated sine (ANA vintage warmth)
 *
 * BANDS=1 to start (kicks live at 40-200 Hz where aliasing is negligible);
 * add band-limited variants only if the voicing harness detects aliasing.
 *
 * Build & run:
 *   cc -std=gnu11 -o /tmp/gen_wt tools/gen_wavetables.c -lm
 *   /tmp/gen_wt > src/wavetables.h
 */
#include <stdio.h>
#include <math.h>

#define TABLE_LEN  2048
#define GUARD_LEN  (TABLE_LEN + 1)   /* 2049 */
#define NUM_WAVES  6
#define BANDS      1

static const float PI = 3.14159265358979323846f;

/* One single-cycle sample for wave `w` at normalized phase p in [0,1). */
static float wave_sample(int w, float p) {
    float ph = 2.0f * PI * p;
    switch (w) {
        case 0:  /* SINE */
            return sinf(ph);
        case 1:  /* TRIANGLE: continuous, peak +/-1 */
            return (p < 0.5f) ? (4.0f * p - 1.0f) : (3.0f - 4.0f * p);
        case 2: { /* SAW-ish: soft ramp, mildly rounded to tame the discontinuity */
            float saw = 2.0f * p - 1.0f;          /* -1..+1 ramp */
            return 0.85f * saw + 0.15f * sinf(ph); /* blend a touch of fundamental */
        }
        case 3:  /* SQUARE */
            return (p < 0.5f) ? 1.0f : -1.0f;
        case 4: { /* DIGITAL: bit-reduced/stepped sine (retro chip crunch) */
            float s = sinf(ph);
            float levels = 8.0f;                  /* ~3-bit steps */
            return roundf(s * levels) / levels;
        }
        case 5: { /* ANALOG: softly saturated sine (vintage warmth) */
            float s = sinf(ph);
            float drive = 1.6f;
            float sat = tanhf(drive * s) / tanhf(drive);  /* normalized to +/-1 */
            return sat;
        }
        default:
            return sinf(ph);
    }
}

int main(void) {
    printf("/* wavetables.h — GENERATED by tools/gen_wavetables.c. Do not edit by hand. */\n");
    printf("#ifndef OMEGA_WAVETABLES_H\n");
    printf("#define OMEGA_WAVETABLES_H\n\n");
    printf("#include <stdalign.h>\n\n");
    printf("/* Band-limited factory wavetables: [wave][band][2048 + 1 guard].\n");
    printf(" * Non-static: dsp_primitives.c owns this definition; other TUs use extern.\n");
    printf(" * NUM_WAVES=%d, BANDS=%d must match src/dsp_primitives.h. */\n",
           NUM_WAVES, BANDS);
    printf("const float _Alignas(16) g_wavetables[%d][%d][%d] = {\n",
           NUM_WAVES, BANDS, GUARD_LEN);

    for (int w = 0; w < NUM_WAVES; w++) {
        printf("  { /* wave %d */\n", w);
        for (int b = 0; b < BANDS; b++) {
            printf("    {\n");
            for (int i = 0; i < GUARD_LEN; i++) {
                int   src = i % TABLE_LEN;    /* index 2048 duplicates index 0 */
                float v   = wave_sample(w, (float)src / (float)TABLE_LEN);
                printf("      %.9ef%s\n", (double)v,
                       (i + 1 < GUARD_LEN) ? "," : "");
            }
            printf("    }%s\n", (b + 1 < BANDS) ? "," : "");
        }
        printf("  }%s\n", (w + 1 < NUM_WAVES) ? "," : "");
    }

    printf("};\n\n");
    printf("#endif /* OMEGA_WAVETABLES_H */\n");
    return 0;
}
